# Site settings
title: Magnus Jahnen | portfolio
description: Software Engineer with focus on machine learning, distributed systems and a little bit of IT security.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "jahnen.me"

# User settings
username: Magnus J. Jahnen
user_description: Software Engineer with focus on machine learning, distributed systems and a little bit of IT security. In addition, I am quite experienced with mobile app development.
user_title: Adventure Capitalist

resume_link: https://nc.jahnen.me/s/NiwL83ZEkngdC8R#pdfviewer

# Google-analytics
google-analytics:
  id: "UA-112460851-1"

exclude: ['package.json', 'src' , 'node_modules']
