# Site settings
title: Magnus J. Jahnen
description: Software Engineer with focus on machine learning, distributed systems and a little bit of IT security. In addition, I am quite experienced with mobile app development.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "jahnen.me"

# User settings
username: Magnus J. Jahnen
user_description: Software Engineer with focus on machine learning, distributed systems and a little bit of IT security. In addition, I am quite experienced with mobile app development.
user_title: Passionate Software Engineer

resume_link: https://www.dropbox.com/s/73xruivkzjih683/resume.pdf?raw=1

# Google-analytics
google-analytics:
  id: "UA-112460851-1"

exclude: ['package.json', 'src' , 'node_modules']
